using Battlemancers.Core.Simulation.Events;

namespace Battlemancers.Core.Simulation.Commands
{
    /// <summary>
    /// Abstract base for all player-issued actions in the simulation.
    ///
    /// Commands are created during the Planning phase, validated at lock-in, and
    /// executed in initiative order during the Resolving phase. Invalid commands are
    /// rejected before resolution begins — execution never needs to handle invalid state.
    ///
    /// In multiplayer, Commands are the payload synced between clients after both players
    /// lock in their plans. The simulation on each client runs the identical command set
    /// to produce a bit-for-bit identical result (deterministic lockstep).
    ///
    /// Pure C# — no Unity dependencies.
    /// </summary>
    public abstract class Command
    {
        /// <summary>
        /// Runtime ID of the unit performing this action.
        /// Must match a unit registered in SimulationState.
        /// </summary>
        public string ActorId { get; }

        /// <summary>
        /// Activation budget cost charged to the owning player when this command is submitted.
        /// Mancers always contribute 100 pts; Chaff and Ranged contribute their PointCost.
        /// TurnManager sums ActivationCost across all commands in a plan to enforce the 100-pt cap.
        /// </summary>
        public int ActivationCost { get; }

        /// <summary>
        /// Initializes the command with the acting unit's ID and activation cost.
        /// </summary>
        /// <param name="actorId">Runtime ID of the unit performing this action.</param>
        /// <param name="activationCost">Budget cost this command contributes to the 100-pt cap.</param>
        protected Command(string actorId, int activationCost)
        {
            ActorId = actorId;
            ActivationCost = activationCost;
        }

        /// <summary>
        /// Returns true if this command can legally be executed given the current simulation state.
        ///
        /// Validate is called at lock-in time before resolution begins. If Validate returns false,
        /// TurnManager rejects the entire plan and surfaces an error to the caller. Execution
        /// is never attempted for invalid commands.
        ///
        /// Implementations should check: unit existence, alive status, range, cooldowns, target
        /// validity, and any type-specific constraints.
        /// </summary>
        /// <param name="state">The current simulation state to validate against.</param>
        /// <returns>True if the command is legal and can be executed; false otherwise.</returns>
        public abstract bool Validate(SimulationState state);

        /// <summary>
        /// Executes the command against the simulation state and returns all events generated.
        ///
        /// The simulation state is mutated during execution (unit positions, HP, cooldowns,
        /// tile occupancy). Callers must ensure Validate() returned true before calling Execute.
        ///
        /// Returns an array of SimulationEvents describing everything that occurred.
        /// The presentation layer consumes these events to drive animation, VFX, and audio.
        /// </summary>
        /// <param name="state">The simulation state to mutate. Must be in Resolving phase.</param>
        /// <returns>All simulation events generated by this command's execution.</returns>
        public abstract SimulationEvent[] Execute(SimulationState state);
    }
}
